### PR TITLE
Correctly traverse from src/foo.rs to src/foo/bar.rs

### LINKED ISSUE #102: Second-level modules not found unless their parent is a `mod.rs`
Given a project structure with `src/lib.rs`:

```rust
mod modules;
```

`src/modules.rs`:

```rust
mod foo;
```

and `src/modules/foo.rs` containing a function that could be mutated, `cargo mutants` does not mutate the function and instead produces a warning and finds no mutants:

```rust
   0.645927098s  WARN src/modules.rs:2: mod Ident { sym: foo, span: bytes(28..31) } not found
```

However, it succeeds if `src/modules.rs` is renamed to `src/modules/mod.rs`.

It seems that `cargo mutants` v1.2.0 is not correctly calculating module paths for children of modules whose source files are not named using the `mod.rs` style.

### PR DESCRIPTION
**Pull request by sourcefrog**
Fixes #102

### CODE REVIEW

**Comment by sourcefrog** [comment]
@kpreid please try this out on the tree where you saw the earlier failure?

**Comment by kpreid** [comment]
> @kpreid please try this out on the tree where you saw the earlier failure?

It is correctly handling most modules now, and proceeds deep enough to then fail on

```rust
mod r#move;
```

by not recognizing that the text of the identifier is `move` rather than `r#move`.

`WARN all-is-cubes/src/block/modifier.rs:8: referent of mod "r#move" not found: tried [".../all-is-cubes/src/block/modifier/r#move.rs", ".../all-is-cubes/src/block/modifier/r#move/mod.rs"]`

There are no other log messages and it is generating mutants for the nested modules (tested in `--list` mode).

**Comment by sourcefrog** [comment]
Great, thanks for the quick feedback. That's a fun edge case.

**Comment by sourcefrog** [comment]
OK, I fixed raw idents and I can also see it's now at least generating all the mutants on all-is-cubes. Please let me know how it goes when you actually test it.

**Comment by kpreid** [comment]
Testing with 0e90cbf1, it seems to be working as intended. There are some warnings due to a different problem but it is not producing any of the previous type and it is generating mutants in all the modules including `move.rs`.

**Pull request merged**
